# EVCC addon for calendar controlled charging

# ical server and check intervall
ical:
  icaluri: http://192.168.0.39:5232/uli/ladekalender.ics/
  chkint: 30 # minutes

# Battery capacity
capa: 64 # kWh

# Max chargecurrent
maxcur: 20 # A

# MQTT server
mqttbroker:
  name: 192.168.0.38
  port: 1883
  user: 
  password: 